apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-site-config
data:
  hive-site.xml: |
    <configuration>
      <!-- Metastore DB -->
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://localhost:5432/metastore</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>hive</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>hivepass</value>
      </property>
      <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>true</value>
      </property>

      <!-- Clients reach HMS via the Service DNS -->
      <property>
        <name>hive.metastore.uris</name>
        <value>thrift://hive-metastore:9083</value>
      </property>

      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>file:///tmp/hive/warehouse</value>
      </property>

      <property>
        <name>write.location-provider.impl</name>
        <value>org.apache.iceberg.hadoop.HadoopLocationProvider</value>
      </property>
    
      <property>
        <name>fs.gs.impl</name>
        <value>com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem</value>
      </property>
      <property>
        <name>fs.AbstractFileSystem.gs.impl</name>
        <value>com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS</value>
      </property>
      
      <property>
        <name>google.cloud.auth.service.account.enable</name>
        <value>true</value>
      </property>
      
      <property>
        <name>google.cloud.auth.service.account.json.keyfile</name>
        <value>/secrets/gcp/SA_keyfile.json</value>
      </property>

      <property>
        <name>fs.defaultFS</name>
        <value>file:///</value>
      </property>
    </configuration>
