---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "trino-ingress"
spec:
  defaultBackend:
    service:
      name: "trino-service"
      port:
        number: 8080
status:
  loadBalancer: {}
