apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coord-config
data:
  config.properties: |
    http-server.process-forwarded=true
    #single node install config
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    discovery.uri=http://localhost:8080
    node.environment=test
    web-ui.authentication.type=FIXED
    web-ui.user=admin
    spiller-spill-path=/mnt/iceberg/spill
    spill-enabled=true
    query.remote-task.max-error-duration=5m
