apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: trino-backendconfig
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    requestPath: /ui/
    port: 8080
    type: HTTP
